### ISSUE TITLE
Error on Android and Apple App using Quelea 2022

### ISSUE THREAD

**Issue by ricardomvalverde** [ArvidNy/quelea-flutter-remote#3]
Testing Quelea 2022 (CI) and Quelea Mobile Remote installed on both iPhone and Android phones, all in same wifi network, we had the following issues:

Android:
It connects, shows the lyrics, but some HTML tags are displayed, making verses not appear centralized or at the top of the screen. The auto search for Quelea server IP works, and it asks for the password automatically after open the app. Clicking arrows to change slides or to go to the next item works.
![image](https://user-images.githubusercontent.com/95576218/146281109-5bf4d86e-7f8f-45f7-8adc-72376f52d33c.png)

iphone:
After opening the app, it presents a default IP 192.168.0.1 and it doesn't automatically searches for the Quelea server IP. After clicking the search button, it finds the Quelea server IP and alters to the correct IP. However, clicking button OK and typing the password, a error is shown.
![image](https://user-images.githubusercontent.com/95576218/146281183-dd672721-ead5-4464-8947-716e3d19bc7d.png)

**Comment by ArvidNy** [comment]
I've just submitted new versions to Google Play and App Store that should resolve the issues. They should be available within a few days (especially depending on the Apple review process). Let me know when you've tried it if it works as expected.

**Comment by ricardomvalverde** [comment]
What a good new! I will test them and I will report you. Thank you so much!
God bless you!

Regards,
Ricardo

Em sex., 28 de jan. de 2022 18:10, Arvid Nyström ***@***.***>
escreveu:

**Comment by ricardomvalverde** [comment]
Hi Arvid!
I just tested both apps in Quelea 2022 and they are working properly!
If I face any bug on next Sundays, I will report you.
Many thanks!!!

Regards,
Ricardo

Em sex., 28 de jan. de 2022 20:15, Ricardo Valverde <
***@***.***> escreveu:

**Comment by ArvidNy** [comment]
Great, thanks for checking!
