### ISSUE TITLE
Adding songs with translation

### ISSUE THREAD

**Issue by thomasvergouwe** [ArvidNy/quelea-flutter-remote#5]
Hi, we often add songs on the fly during our church services. We also use the app to control Quelea.
We have it set in the settings that quelea would always use the translation when adding a song. However, when we add a song through the app to the service, quelea doesn’t automatically use the translation.

Can this be added?

**Comment by ArvidNy** [comment]
Thanks for reporting this. However, I'd say this is more of a server issue than an app bug, so I will have to ask you to instead open an issue for this in [the main repository](https://github.com/quelea-projection/Quelea/issues).
